### ISSUE TITLE
Dynamic deranged

### ISSUE THREAD

**Issue by Zizico2** [jhpratt/deranged#14]
Is there any chance we get a dynamic version of this crate? I have implemented a subset of this crate in something I'm working on that requires wrapping arithmetic. It has to be dynamic though. I need to be able to choose the wrapping interval at runtime. Is there any chance this could be included in this crate? I'd be willing to create a PR. I assume most of the code would be reusable, just replacing const generics with parameters. Or should I just make this a crate by itself?

**Comment by jhpratt** [comment]
The primary benefit of `deranged` is being able to use the types with zero additional cost. Doing this at runtime isn't possible given that it would necessarily triple the size of the type.

**Comment by Zizico2** [comment]
Ok I understand. 
I'm still using deranged instead of using my own version as I don't trust myself that much c;.
I've just ended up doing something like this since the number of ranges is I'm interested in is small anyway.
```
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Eq, Ord)]
enum DynamicDeranged {
    U32_0_19(RangedU32<0, 19>),
    U32_0_18(RangedU32<0, 18>),
}
```
And I just forward every method.

**Comment by Easyoakland** [comment]
@jhpratt 
What about defining a module for the actual functions definitions and both forwarding to those and exposing them?
Something like [this](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywZ7HAGTwNMAHLuAEaYxCAAzBqkAA6oCoR2DC5uHnpxCbYCvv5BLKHhUZaY1lkMQgRMxAQp7p5cxaVJFVUEOYEhYZHR5q21aQ291e15Bd0AlJaoJsTI7BwA9EsA1ACCtMAkhAgsCssECEwEy5iqGZjLeCwxtHv8xMvoAJ7MLHjIy2aYe0x7AO4lWjLX7LXq2ZAAUg0qxiJmCyxYGGBG1QywhAHYAEJQ1bLPFogBMEQhAFZMX5aH5MKSACI4/HLWHwtAMczLKgMZb%2BP4AfQURxmRz8wAgb08nwSAC9MKQEUx1BK8NLZQA3MQmdiK6XjZYAWghEWwWouGOx0IZDN%2BSmqYEgYrREScBppctU4wNZtxFrxeCoyzVbhNjoRfjRWPp3otYoj3oxLpKSkufoDGodRpY8rDnsjUflMYtcZOtxN4fNOfxKepZdj6Lp1bDddWcZxOPMphsyyEBqcLLZAFkAJIBEDG2W94591YADRHZiV1MNEDn2o9OKuN274%2BWg%2BHo%2BWW8nM%2BNBqNXcdO9lh5PWfzW9WQiE2AASgAVEcQHXO4EKa0EW0QHcHSdCIXUPd0ImzfEISJUlyQYSl/FpfMmX3AQ2Q5LlMF5fkCEFWwjAgStZylTAdX1Q1O27C9t2na9TXzBkhBKKgQBAe9H1fVd60YiAxE2VjuT5AViCFAjqMPVV1VI9162baE5KbaEvlBAh0FYhA/AIVjggMZAAGseWCVBVC41YVjEIE/FhAg9gOI5lj%2BaZaHQZZQkeF5WHeCynmWYBGDCI5MBcqoLj%2BESYhiILLk5CEADYNB0ph9MM4y4o0AA6FtoRWAc/SeaYJRNeKMz8D80tlLBkAMYgLkIb80Xipk0v2VElFq45QwOC5pgIayQBbGCyQYVAeQzIx6CQ6EUIwkqGB5Z5XneD8szRet6GOAMHRdPjUAErChNwkT8JFRLkqM1QIEkSZToM86IBJa7dNu4yIFi8ZwMgvEbpSi6Aw%2BltawG4khpGsbgAmklG2mzlZr5SpwWW%2Bi1swDaxC2ztWO7ElSFik89uw4TRJOp6fte97TIZb67r%2B0yFI4SZaE4EleE8DgtFIXaOCfMxjgUaZZhNIkeFILS2fpyY9JAElokZjhJBZzReE53gFBAaJRa0SY4FgJA0GuOgwnISg9ZiA3wmILh0Wlvg6AIMJVYgYJFdIYI/CqJ5OGF13mGIJ4AHlgm0TAbE93g9bYQQ/fgj2xdILBghMYAnAs1XuF4LAwfEWP8Bqmw8BVb5ndOYOTDt0PyEEEpncpYIRN9lwsGdghiCuUPJioAxgAUAA1PAsL9yLWeF/hBBEMR2CkGRBEUFR1Fj3QGgMIwQFMcx9DwYJVcgSZUBiMpU91Jxll3ghdXoAvaGdYXUAL4gW6wLeP0aYOygcBhnFcOovHfkZOnCBoMiJAEP0eosR4hAIYL/fIXRBglBfs0So1QQF6CsPAgQLRhhUlGDAywiCaifwGLg1oUCxhcEmHzGYcwJAMyZgrWOnNlirwIB8Lg6UrbpQ0MsCAuBCAkEJBEMhvANb01IBAJAPVrJGwgCbM2ARWDzCYSwthJIOG8CCrw%2B%2BegR7CFEOISe2iZ5qGdgvUgYUmAxDbvoWhpBWbs05n7Uu1lj5%2BkUcsVh7DOEQBcPregDxoICPGEIxW71SCS2trLeWNjnbK0sGrEWwSaEcAJHQuxnAglixCbfBI9hJBAA%3D%3D)
```rust
/// Algorithms that expose impls for dynamic uses as well as static
pub mod algo {
    #[inline]
    pub const fn new_saturating(min: usize, max: usize, value: usize) -> usize {
        assert!(min <= max);
        if value < min {
            min
        } else if value > max {
            max
        } else {
            value
        }
    }
}

struct S<const MIN: usize, const MAX: usize>(usize);
impl<const MIN: usize, const MAX: usize> S<MIN, MAX> {
    const ASSERT: () = assert!(MIN <= MAX);
    #[inline]
    pub const fn new_saturating(value: usize) -> S<MIN, MAX> {
        Self::ASSERT;
        S(algo::new_saturating(MIN, MAX, value))
    }
}

use std::hint::black_box;
// all inputs that would be dynamically generated are wrapped in `black_box`.

// If you use `main()`, declare it as `pub` to see it in the output:
#[no_mangle]
pub fn main_dynamic() { 
    let val = algo::new_saturating(black_box(4),black_box(5),black_box(6));
    black_box(val);
}
#[no_mangle]
pub fn main_static() {
    let val = S::<5,6>::new_saturating(black_box(6));
    black_box(val);
}
```

- When the functions are inlined (opt-level >0) the static version compiles to the same thing as if there were no extra function call.
- In the dynamic case the setting is saved once somewhere and refered to many times, preventing a tripling of the size of the many integers.
- This would be useful, at least to me, to expose the different algorithms meant for ranged arithmetic. For example for a game with dynamically sized toroidal/wrapping grid coordinates like in Pacman.

**Comment by Easyoakland** [comment]
Although in the above case `.clamp(min,max)` could work instead, this could also be applied to `saturating_{abs, add, sub, mul, ...}`, `checked_{add,sub,pow,...}`, `wrapping_{add,sub...}`, etc.

**Comment by jhpratt** [comment]
@Easyoakland The goal of this crate is to be a testing ground for a future where ranged integers exist in the standard library, I don't think exposing internals in that manner would make sense.

**Comment by Easyoakland** [comment]
@jhpratt I'm not sure I understand why this would be considered "exposing internals". It would be providing the same api that is already provided (but `ranged_method(min,max,val)` instead of `RangedType::<MIN, MAX>(val)` . It would not be exposing the implementations of these functions. If the implementation had to change it would not be prevented these dynamic versions being available.

**Comment by jhpratt** [comment]
Yes, but that API is not something that I intend to propose for the standard library. The `Option`-like types only exist to provide (limited) niche value optimization, with every other aspect of the library being intended to be part of `std` in the future (in some form or another). Adding methods like what you're proposing would deviate from that.

**Comment by Easyoakland** [comment]
It sounds like you don't believe there would be a benefit to including these dynamic ranged functions in `std`. If not included, the alternative is to copy the implementations and add them to another crate.
Do you believe avoiding this duplication is not worthwhile? Or is there a different reason you don't think they should be proposed?

**Comment by jhpratt** [comment]
I do not believe that such a function would be accepted for inclusion to `std` if proposed, that is correct.
